trigger:
- main  # Trigger on push to 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted Ubuntu agent

steps:
- task: Checkout@1
  displayName: 'Checkout code'

- script: echo "Build step"
  displayName: 'Build the project'

- script: echo "Running tests"
  displayName: 'Test step'

- script: echo "Deploy step"
  displayName: 'Deploy the project'
